package com.bondevans.fretboard.firebase;

import android.content.Context;
import android.util.Log;

import com.bondevans.fretboard.firebase.dao.Songs;
import com.bondevans.fretboard.firebase.dao.SongClick;
import com.bondevans.fretboard.firebase.dao.Users;
import com.bondevans.fretboard.fretview.FretSong;
import com.firebase.client.Firebase;

import java.util.HashMap;
import java.util.Map;

/**
 * @author Paul Evans
 * @since 16/11/15
 *
 * Convenience class for writing stuff to the Firebase NOSQL Database
 */
public class FBWrite {
    private static final String TAG = FBWrite.class.getSimpleName();

    public static void newUser(Context context, Firebase firebaseRef, String uid, Users user) {
        firebaseRef.child(Users.childName).child(uid).setValue(user);
        // TODO Also add some device details
//        DeviceDetails device = new DeviceDetails(context);
//        firebaseRef.child("users").child(uid).push().setValue(device);
    }

    public static void usage(Firebase firebaseRef, String uId, String songId) {
        SongClick songClick = new SongClick(songId, uId);
        firebaseRef.child(SongClick.childName).child(uId).push().setValue(songClick);
    }

    /**
     * Add a new Song to the firebase db
     * @param firebaseRef firebase reference
     * @param fretSong FretSoong to add to db
     * @param description Description of the song
     */
    public static void addSong(Firebase firebaseRef, FretSong fretSong, String description) {
        // First add the song contents - create a new record
        Firebase contentsRef = firebaseRef.child("songcontents").push();
        // Get the unique ID generated by push()
        String songId = contentsRef.getKey();
        Log.d(TAG, "SongRef=[" + songId + "]");
        Map<String, String> post1 = new HashMap<>();
        post1.put("contents", fretSong.toString());
        contentsRef.setValue(post1);
        // Now store the Song Details entry using id as link to contents
        Firebase detailsRef = firebaseRef.child("songs");
        // TODO Add uploadedBy, dateUploaded, etc details
        detailsRef.push().setValue(new Songs(songId, fretSong.getName(), description));
    }
}
