package com.bondevans.frets.firebase;

import android.content.Context;
import android.util.Log;

import com.bondevans.frets.firebase.dao.Fret;
import com.bondevans.frets.firebase.dao.SongClick;
import com.bondevans.frets.firebase.dao.Users;
import com.bondevans.frets.fretview.FretSong;
import com.google.firebase.database.DatabaseReference;

import java.util.HashMap;
import java.util.Map;

/**
 * @author Paul Evans
 * @since 16/11/15
 *
 * Convenience class for writing stuff to the Firebase NOSQL Database
 */
public class FBWrite {
    private static final String TAG = FBWrite.class.getSimpleName();

    public static void newUser(Context context, DatabaseReference firebaseRef, String uid, Users user) {
        firebaseRef.child(Users.childName).child(uid).setValue(user);
        // TODO Also add some device details
//        DeviceDetails device = new DeviceDetails(context);
//        firebaseRef.child("users").child(uid).push().setValue(device);
    }

    public static void usage(DatabaseReference firebaseRef, String uId, String songId) {
        SongClick songClick = new SongClick(songId, uId);
        firebaseRef.child(SongClick.childName).child(uId).push().setValue(songClick);
    }

    /**
     * Add a new Song to the firebase db
     * @param firebaseRef firebase reference
     * @param fretSong FretSong to add to db
     */
    public static void addSong(DatabaseReference firebaseRef, FretSong fretSong, String uid) {
        // First add the song contents - create a new record
        DatabaseReference contentsRef = firebaseRef.child("songcontents").push();
        // Get the unique ID generated by push()
        String songId = contentsRef.getKey();
        Log.d(TAG, "SongRef=[" + songId + "]");
        Map<String, String> post1 = new HashMap<>();
        post1.put("contents", fretSong.toString());
        contentsRef.setValue(post1);
        // Now store the Song Details entry using id as link to contents
        DatabaseReference detailsRef = firebaseRef.child("users").child(uid).child("frets");
        // TODO Add uploadedBy, dateUploaded, etc details
        detailsRef.push().setValue(new Fret(songId, fretSong.getName(), fretSong.getKeywords()));
    }

    /**
     * Delete a Song from the firebase db
     * @param firebaseRef firebase reference
     * @param uid User Id
     * @param fretId song Id
     */
    public static void deletePrivateSong(DatabaseReference firebaseRef, String uid, String fretId) {
        Log.d(TAG, "HELLO deletePrivateSong SongRef=[" + fretId + "] user Id=["+uid+"]");
        // First remove the fret
        DatabaseReference songRef = firebaseRef.child("user").child(uid).child("frets").child(fretId);
        songRef.removeValue();
        // Now the song contents
        DatabaseReference contentsRef = firebaseRef.child("songcontents").child(fretId);
        contentsRef.removeValue();
    }

}
